package safecityserver.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import safecityserver.entities.Type;
import safecityserver.repos.TypeRepo;

@Controller // This means that this class is a Controller
@RequestMapping(path="/type") // This means URL's start with /demo (after Application path)
public class TypeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TypeRepo typeRepo;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String typeName) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Type type = new Type();
        type.setNameType(typeName);
        typeRepo.save(type);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Type> getAllTypes() {
        // This returns a JSON or XML with the users
        return typeRepo.findAll();
    }
}